# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\CustomDataSelectionWidget\CustomDataSelectionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomDataSelectionWidget(object):
    def setupUi(self, CustomDataSelectionWidget):
        CustomDataSelectionWidget.setObjectName("CustomDataSelectionWidget")
        CustomDataSelectionWidget.resize(424, 300)
        self.formLayout = QtWidgets.QFormLayout(CustomDataSelectionWidget)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(CustomDataSelectionWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(CustomDataSelectionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setBaseSize(QtCore.QSize(100, 0))
        self.lineEdit.setToolTip("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(CustomDataSelectionWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.horizontalLayout_2.setStretch(1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.widget = CustomDataSelectionWidget_Subpanel_SimpleXY(CustomDataSelectionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(400, 79))
        self.widget.setBaseSize(QtCore.QSize(400, 79))
        self.widget.setObjectName("widget")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFinalizeLoad = ThreadPoolPushButton(CustomDataSelectionWidget)
        self.btnFinalizeLoad.setDefault(True)
        self.btnFinalizeLoad.setObjectName("btnFinalizeLoad")
        self.horizontalLayout.addWidget(self.btnFinalizeLoad)
        self.btnCancel = QtWidgets.QPushButton(CustomDataSelectionWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)

        self.retranslateUi(CustomDataSelectionWidget)
        QtCore.QMetaObject.connectSlotsByName(CustomDataSelectionWidget)

    def retranslateUi(self, CustomDataSelectionWidget):
        _translate = QtCore.QCoreApplication.translate
        CustomDataSelectionWidget.setWindowTitle(_translate("CustomDataSelectionWidget", "CustomDataSelectionWidget"))
        self.label.setText(_translate("CustomDataSelectionWidget", "timestamps"))
        self.toolButton.setText(_translate("CustomDataSelectionWidget", "..."))
        self.btnFinalizeLoad.setText(_translate("CustomDataSelectionWidget", "Load"))
        self.btnCancel.setText(_translate("CustomDataSelectionWidget", "Cancel"))
from phopyqttimelineplotter.GUI.UI.CustomDataSelectionWidget.CustomDataSelectionWidget_Subpanel_SimpleXY import CustomDataSelectionWidget_Subpanel_SimpleXY
from silx.gui.widgets.ThreadPoolPushButton import ThreadPoolPushButton
