# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\CustomDataSelectionWidget\CustomDataSelectionWidget_Subpanel_SimpleXY.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomDataSelectionWidget_Subpanel_SimpleXY(object):
    def setupUi(self, CustomDataSelectionWidget_Subpanel_SimpleXY):
        CustomDataSelectionWidget_Subpanel_SimpleXY.setObjectName(
            "CustomDataSelectionWidget_Subpanel_SimpleXY"
        )
        CustomDataSelectionWidget_Subpanel_SimpleXY.resize(400, 79)
        self.layoutWidget = QtWidgets.QWidget(
            CustomDataSelectionWidget_Subpanel_SimpleXY
        )
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 382, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setBaseSize(QtCore.QSize(100, 0))
        self.lineEdit.setToolTip("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.horizontalLayout_2.setStretch(1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(
            CustomDataSelectionWidget_Subpanel_SimpleXY
        )
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 382, 24))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_2.setBaseSize(QtCore.QSize(100, 0))
        self.lineEdit_2.setToolTip("")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.toolButton_2 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.horizontalLayout_3.setStretch(1, 1)

        self.retranslateUi(CustomDataSelectionWidget_Subpanel_SimpleXY)
        QtCore.QMetaObject.connectSlotsByName(
            CustomDataSelectionWidget_Subpanel_SimpleXY
        )

    def retranslateUi(self, CustomDataSelectionWidget_Subpanel_SimpleXY):
        _translate = QtCore.QCoreApplication.translate
        CustomDataSelectionWidget_Subpanel_SimpleXY.setWindowTitle(
            _translate(
                "CustomDataSelectionWidget_Subpanel_SimpleXY",
                "CustomDataSelectionWidget_Subpanel_SimpleXY",
            )
        )
        self.label.setText(
            _translate("CustomDataSelectionWidget_Subpanel_SimpleXY", "x")
        )
        self.toolButton.setText(
            _translate("CustomDataSelectionWidget_Subpanel_SimpleXY", "...")
        )
        self.label_2.setText(
            _translate("CustomDataSelectionWidget_Subpanel_SimpleXY", "y")
        )
        self.toolButton_2.setText(
            _translate("CustomDataSelectionWidget_Subpanel_SimpleXY", "...")
        )
