# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\TimelineFloatingHeaderWidget\TimelineFloatingHeaderWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimelineFloatingHeaderWidget(object):
    def setupUi(self, TimelineFloatingHeaderWidget):
        TimelineFloatingHeaderWidget.setObjectName("TimelineFloatingHeaderWidget")
        TimelineFloatingHeaderWidget.resize(337, 82)
        TimelineFloatingHeaderWidget.setMinimumSize(QtCore.QSize(0, 82))
        TimelineFloatingHeaderWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(30, 30, 30, 40), stop:1 rgba(60, 66, 60, 40));\n"
"color:rgb(243, 243, 243);\n"
"hover { background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(30, 30, 30, 200), stop:1 rgba(60, 66, 60, 200)); backcolor:white };\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TimelineFloatingHeaderWidget)
        self.verticalLayout_2.setContentsMargins(2, 2, 0, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_TopButtons = QtWidgets.QFrame(TimelineFloatingHeaderWidget)
        self.frame_TopButtons.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_TopButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopButtons.setLineWidth(1)
        self.frame_TopButtons.setObjectName("frame_TopButtons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_TopButtons)
        self.horizontalLayout_3.setContentsMargins(2, 2, 0, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(self.frame_TopButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: rgb(250, 250, 250)")
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(self.frame_TopButtons)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblSubtitle.setFont(font)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout.addWidget(self.lblSubtitle)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.btnFindNext = QtWidgets.QPushButton(self.frame_TopButtons)
        self.btnFindNext.setText("")
        self.btnFindNext.setObjectName("btnFindNext")
        self.horizontalLayout_3.addWidget(self.btnFindNext)
        self.btnOptions = QtWidgets.QPushButton(self.frame_TopButtons)
        self.btnOptions.setText("")
        self.btnOptions.setObjectName("btnOptions")
        self.horizontalLayout_3.addWidget(self.btnOptions)
        self.btnRefresh = QtWidgets.QPushButton(self.frame_TopButtons)
        self.btnRefresh.setText("")
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_3.addWidget(self.btnRefresh)
        self.verticalLayout_2.addWidget(self.frame_TopButtons)

        self.retranslateUi(TimelineFloatingHeaderWidget)
        QtCore.QMetaObject.connectSlotsByName(TimelineFloatingHeaderWidget)

    def retranslateUi(self, TimelineFloatingHeaderWidget):
        _translate = QtCore.QCoreApplication.translate
        TimelineFloatingHeaderWidget.setWindowTitle(_translate("TimelineFloatingHeaderWidget", "Floating Track Header Widget"))
        self.lblTitle.setText(_translate("TimelineFloatingHeaderWidget", "Track 00"))
        self.lblSubtitle.setText(_translate("TimelineFloatingHeaderWidget", "Subtitle"))
        self.btnFindNext.setToolTip(_translate("TimelineFloatingHeaderWidget", "Collapse"))
        self.btnFindNext.setStatusTip(_translate("TimelineFloatingHeaderWidget", "Collapse"))
        self.btnFindNext.setAccessibleName(_translate("TimelineFloatingHeaderWidget", "Collapse"))
        self.btnOptions.setToolTip(_translate("TimelineFloatingHeaderWidget", "Options"))
        self.btnOptions.setStatusTip(_translate("TimelineFloatingHeaderWidget", "Options"))
        self.btnOptions.setAccessibleName(_translate("TimelineFloatingHeaderWidget", "Options"))
        self.btnRefresh.setToolTip(_translate("TimelineFloatingHeaderWidget", "Refresh"))
        self.btnRefresh.setStatusTip(_translate("TimelineFloatingHeaderWidget", "Refresh"))
        self.btnRefresh.setAccessibleName(_translate("TimelineFloatingHeaderWidget", "Refresh"))
