# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\VideoEditDialog\VideoEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 527)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_StartEndDates = DialogComponents_StartEndDate(Dialog)
        self.frame_StartEndDates.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_StartEndDates.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_StartEndDates.setObjectName("frame_StartEndDates")
        self.verticalLayout.addWidget(self.frame_StartEndDates)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_isOriginalVideo = QtWidgets.QCheckBox(self.frame)
        self.checkBox_isOriginalVideo.setObjectName("checkBox_isOriginalVideo")
        self.verticalLayout_2.addWidget(self.checkBox_isOriginalVideo)
        self.verticalLayout.addWidget(self.frame)
        self.frame_BoxExperCohortAnimalIDs = DialogComponents_BoxExperCohortAnimalIDs(Dialog)
        self.frame_BoxExperCohortAnimalIDs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BoxExperCohortAnimalIDs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_BoxExperCohortAnimalIDs.setObjectName("frame_BoxExperCohortAnimalIDs")
        self.verticalLayout.addWidget(self.frame_BoxExperCohortAnimalIDs)
        self.frame_TypeSubtype = DialogComponents_TypeSubtype(Dialog)
        self.frame_TypeSubtype.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TypeSubtype.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TypeSubtype.setObjectName("frame_TypeSubtype")
        self.verticalLayout.addWidget(self.frame_TypeSubtype)
        self.frame_TitleSubtitleBody = DialogComponents_TitleSubtitleBody(Dialog)
        self.frame_TitleSubtitleBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TitleSubtitleBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TitleSubtitleBody.setObjectName("frame_TitleSubtitleBody")
        self.verticalLayout.addWidget(self.frame_TitleSubtitleBody)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox_isOriginalVideo.setText(_translate("Dialog", "is Original Video"))
from GUI.UI.DialogComponents.DialogComponents_BoxExperCohortAnimalIDs import DialogComponents_BoxExperCohortAnimalIDs
from GUI.UI.DialogComponents.DialogComponents_StartEndDate import DialogComponents_StartEndDate
from GUI.UI.DialogComponents.DialogComponents_TitleSubtitleBody import DialogComponents_TitleSubtitleBody
from GUI.UI.DialogComponents.DialogComponents_TypeSubtype import DialogComponents_TypeSubtype
