# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\ReferenceMarkViewer\DockWidget_ReferenceMarkViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget_ReferenceMarkViewer(object):
    def setupUi(self, DockWidget_ReferenceMarkViewer):
        DockWidget_ReferenceMarkViewer.setObjectName("DockWidget_ReferenceMarkViewer")
        DockWidget_ReferenceMarkViewer.setWindowModality(QtCore.Qt.ApplicationModal)
        DockWidget_ReferenceMarkViewer.resize(400, 300)
        DockWidget_ReferenceMarkViewer.setFloating(True)

        self.retranslateUi(DockWidget_ReferenceMarkViewer)
        QtCore.QMetaObject.connectSlotsByName(DockWidget_ReferenceMarkViewer)

    def retranslateUi(self, DockWidget_ReferenceMarkViewer):
        _translate = QtCore.QCoreApplication.translate
        DockWidget_ReferenceMarkViewer.setWindowTitle(_translate("DockWidget_ReferenceMarkViewer", "Reference Mark Viewer"))
