# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\ImportCSVWidget\ImportCSVWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportCsvWidget(object):
    def setupUi(self, ImportCsvWidget):
        ImportCsvWidget.setObjectName("ImportCsvWidget")
        ImportCsvWidget.resize(761, 635)
        self.gridLayout = QtWidgets.QGridLayout(ImportCsvWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(ImportCsvWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.importContextMain = ImportContext_DialogComponents(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importContextMain.sizePolicy().hasHeightForWidth())
        self.importContextMain.setSizePolicy(sizePolicy)
        self.importContextMain.setObjectName("importContextMain")
        self.verticalLayout.addWidget(self.importContextMain)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(ImportCsvWidget)
        QtCore.QMetaObject.connectSlotsByName(ImportCsvWidget)

    def retranslateUi(self, ImportCsvWidget):
        _translate = QtCore.QCoreApplication.translate
        ImportCsvWidget.setWindowTitle(_translate("ImportCsvWidget", "Form"))
        self.label.setText(_translate("ImportCsvWidget", "Import Labjack Data"))
from GUI.UI.DialogComponents.ImportContext_DialogComponents import ImportContext_DialogComponents
