
def get_behaviors_list():
    return ['Awaken',
        'Chew',
        'Come Down',
        'Come Down From Partially Reared',
        'Come Down To Partially Reared',
        'ComeDown(CDtoPR, CDfromPR)',
        'Dig',
        'Drink Spout1',
        'Eat Zone1',
        'Eat Zone2',
        'Forage',
        'Groom',
        'Hang Cuddled',
        'Hang Vertically From Rear Up',
        'HangCuddled(HangCudl, RemainHC)',
        'HangVertically From HangCuddled',
        'HangVertically(HVfromHC, RemainHV)',
        'HangVertically(HVfromRU, HVfromHC, RemainHV)',
        'HangVertically(HVfromRU, RemainHV)',
        'HangVertically(HVfromRU, RemainHV, HVfromRU)',
        'HangVertically(HVfromRU, RemainHV, HVfromRU, RemainHV)',
        'HangVertically(HVfromRU, RemainHV, HVfromRU, RemainHV, HVfromRU, RemainHV)',
        'Jump',
        'Land Vertically',
        'Pause',
        'Rear Up',
        'Rear up Full From Partial',
        'Rear up Partially',
        'RearUp(RUfromPR, RemainRU)',
        'RearUp(RUfromPR, RemainRU, RUfromPR, RemainRU)',
        'RearUp(RUtoPR, RUfromPR)',
        'RearUp(RUtoPR, RUfromPR, RemainRU)',
        'RearUp(RearUp, RemainRU)',
        'Remain Hang Cuddled',
        'Remain Hang Vertically',
        'Remain Low',
        'Remain Partially Reared',
        'Remain RearUp',
        'Sleep',
        'Sniff',
        'Stationary',
        'Stretch Body',
        'Turn',
        'Twitch',
        'Unknown Behavior',
        'Walk Left',
        'Walk Right',
        'Walk Slowly'
    ]

def get_behaviors_groups_list():
    return ['Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Drink',
        'Eat',
        'Eat',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Resting Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Sleep',
        'Active Wakefulness',
        'Resting Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness',
        'Unknown Behavior',
        'Active Wakefulness',
        'Active Wakefulness',
        'Active Wakefulness'
    ]