# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\DialogComponents\ImportContext_DialogComponents.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(606, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locklist_Box = LockableList(self.frame)
        self.locklist_Box.setObjectName("locklist_Box")
        self.horizontalLayout.addWidget(self.locklist_Box)
        self.locklist_Animal = LockableList(self.frame)
        self.locklist_Animal.setObjectName("locklist_Animal")
        self.horizontalLayout.addWidget(self.locklist_Animal)
        self.locklist_Cohort = LockableList(self.frame)
        self.locklist_Cohort.setObjectName("locklist_Cohort")
        self.horizontalLayout.addWidget(self.locklist_Cohort)
        self.locklist_Labjack = LockableList(self.frame)
        self.locklist_Labjack.setObjectName("locklist_Labjack")
        self.horizontalLayout.addWidget(self.locklist_Labjack)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from GUI.UI.DialogComponents.LockableList import LockableList
