# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\DialogComponents\LockableList.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(374, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_frame = QtWidgets.QFrame(self.frame)
        self.list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list_frame.setObjectName("list_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.list_frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_main_content = QtWidgets.QFrame(self.list_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main_content.sizePolicy().hasHeightForWidth())
        self.frame_main_content.setSizePolicy(sizePolicy)
        self.frame_main_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_content.setObjectName("frame_main_content")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_main_content)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listView = QtWidgets.QListView(self.frame_main_content)
        self.listView.setObjectName("listView")
        self.gridLayout_4.addWidget(self.listView, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.frame_main_content)
        self.tableView.setMinimumSize(QtCore.QSize(100, 120))
        self.tableView.setBaseSize(QtCore.QSize(100, 120))
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setObjectName("tableView")
        self.gridLayout_4.addWidget(self.tableView, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_main_content, 1, 0, 1, 1)
        self.lblListTitle = QtWidgets.QLabel(self.list_frame)
        self.lblListTitle.setMinimumSize(QtCore.QSize(90, 13))
        self.lblListTitle.setBaseSize(QtCore.QSize(90, 13))
        self.lblListTitle.setObjectName("lblListTitle")
        self.gridLayout_3.addWidget(self.lblListTitle, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.list_frame)
        self.edit_buttons_frame = QtWidgets.QFrame(self.frame)
        self.edit_buttons_frame.setMinimumSize(QtCore.QSize(0, 24))
        self.edit_buttons_frame.setMaximumSize(QtCore.QSize(16777215, 24))
        self.edit_buttons_frame.setBaseSize(QtCore.QSize(0, 24))
        self.edit_buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_buttons_frame.setObjectName("edit_buttons_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.edit_buttons_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listLockableEditWidget = ListLockableEditButtons_DialogComponents(self.edit_buttons_frame)
        self.listLockableEditWidget.setMinimumSize(QtCore.QSize(90, 19))
        self.listLockableEditWidget.setMaximumSize(QtCore.QSize(16777215, 22))
        self.listLockableEditWidget.setBaseSize(QtCore.QSize(90, 19))
        self.listLockableEditWidget.setObjectName("listLockableEditWidget")
        self.gridLayout.addWidget(self.listLockableEditWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.edit_buttons_frame)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblListTitle.setText(_translate("Form", "List Title"))
from GUI.UI.DialogComponents.ListLockableEditButtons_DialogComponents import ListLockableEditButtons_DialogComponents
