# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\DialogComponents\StartEndDate_DialogComponents.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame_StartEndDatetime(object):
    def setupUi(self, Frame_StartEndDatetime):
        Frame_StartEndDatetime.setObjectName("Frame_StartEndDatetime")
        Frame_StartEndDatetime.resize(406, 76)
        self.formLayout = QtWidgets.QFormLayout(Frame_StartEndDatetime)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Frame_StartEndDatetime)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.dateTimeEdit_Start = QtWidgets.QDateTimeEdit(Frame_StartEndDatetime)
        self.dateTimeEdit_Start.setObjectName("dateTimeEdit_Start")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit_Start)
        self.label_2 = QtWidgets.QLabel(Frame_StartEndDatetime)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dateTimeEdit_End = QtWidgets.QDateTimeEdit(Frame_StartEndDatetime)
        self.dateTimeEdit_End.setEnabled(True)
        self.dateTimeEdit_End.setObjectName("dateTimeEdit_End")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit_End)

        self.retranslateUi(Frame_StartEndDatetime)
        QtCore.QMetaObject.connectSlotsByName(Frame_StartEndDatetime)

    def retranslateUi(self, Frame_StartEndDatetime):
        _translate = QtCore.QCoreApplication.translate
        Frame_StartEndDatetime.setWindowTitle(_translate("Frame_StartEndDatetime", "Frame"))
        self.label.setText(_translate("Frame_StartEndDatetime", "startDate"))
        self.label_2.setText(_translate("Frame_StartEndDatetime", "endDate"))
