# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\DialogComponents\TypeSubtype_DialogComponents.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame_TypeSubtype(object):
    def setupUi(self, Frame_TypeSubtype):
        Frame_TypeSubtype.setObjectName("Frame_TypeSubtype")
        Frame_TypeSubtype.resize(168, 86)
        self.formLayout = QtWidgets.QFormLayout(Frame_TypeSubtype)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(Frame_TypeSubtype)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_Type = QtWidgets.QComboBox(Frame_TypeSubtype)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_Type)
        self.label_7 = QtWidgets.QLabel(Frame_TypeSubtype)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_Subtype = QtWidgets.QComboBox(Frame_TypeSubtype)
        self.comboBox_Subtype.setObjectName("comboBox_Subtype")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_Subtype)

        self.retranslateUi(Frame_TypeSubtype)
        QtCore.QMetaObject.connectSlotsByName(Frame_TypeSubtype)

    def retranslateUi(self, Frame_TypeSubtype):
        _translate = QtCore.QCoreApplication.translate
        Frame_TypeSubtype.setWindowTitle(_translate("Frame_TypeSubtype", "Frame"))
        self.label_6.setText(_translate("Frame_TypeSubtype", "Type"))
        self.label_7.setText(_translate("Frame_TypeSubtype", "Subtype"))
