# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\DialogComponents\TitleSubtitleBody_DialogComponents.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame_TitleSubtitleBody(object):
    def setupUi(self, Frame_TitleSubtitleBody):
        Frame_TitleSubtitleBody.setObjectName("Frame_TitleSubtitleBody")
        Frame_TitleSubtitleBody.resize(405, 256)
        self.formLayout = QtWidgets.QFormLayout(Frame_TitleSubtitleBody)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Frame_TitleSubtitleBody)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_Title = QtWidgets.QLineEdit(Frame_TitleSubtitleBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Title.sizePolicy().hasHeightForWidth())
        self.lineEdit_Title.setSizePolicy(sizePolicy)
        self.lineEdit_Title.setClearButtonEnabled(True)
        self.lineEdit_Title.setObjectName("lineEdit_Title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Title)
        self.label_4 = QtWidgets.QLabel(Frame_TitleSubtitleBody)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_Subtitle = QtWidgets.QLineEdit(Frame_TitleSubtitleBody)
        self.lineEdit_Subtitle.setClearButtonEnabled(True)
        self.lineEdit_Subtitle.setObjectName("lineEdit_Subtitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Subtitle)
        self.label_5 = QtWidgets.QLabel(Frame_TitleSubtitleBody)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.textBrowser_Body = QtWidgets.QTextBrowser(Frame_TitleSubtitleBody)
        self.textBrowser_Body.setReadOnly(False)
        self.textBrowser_Body.setObjectName("textBrowser_Body")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textBrowser_Body)

        self.retranslateUi(Frame_TitleSubtitleBody)
        QtCore.QMetaObject.connectSlotsByName(Frame_TitleSubtitleBody)

    def retranslateUi(self, Frame_TitleSubtitleBody):
        _translate = QtCore.QCoreApplication.translate
        Frame_TitleSubtitleBody.setWindowTitle(_translate("Frame_TitleSubtitleBody", "Frame"))
        self.label_3.setText(_translate("Frame_TitleSubtitleBody", "Title"))
        self.lineEdit_Title.setText(_translate("Frame_TitleSubtitleBody", "title"))
        self.lineEdit_Title.setPlaceholderText(_translate("Frame_TitleSubtitleBody", "title"))
        self.label_4.setText(_translate("Frame_TitleSubtitleBody", "Subtitle"))
        self.lineEdit_Subtitle.setText(_translate("Frame_TitleSubtitleBody", "subtitle"))
        self.lineEdit_Subtitle.setPlaceholderText(_translate("Frame_TitleSubtitleBody", "subtitle"))
        self.label_5.setText(_translate("Frame_TitleSubtitleBody", "Body"))
        self.textBrowser_Body.setPlaceholderText(_translate("Frame_TitleSubtitleBody", "body text"))
