# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\TextAnnotations\TextAnnotations.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextAnnotationDialog(object):
    def setupUi(self, TextAnnotationDialog):
        TextAnnotationDialog.setObjectName("TextAnnotationDialog")
        TextAnnotationDialog.resize(519, 436)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextAnnotationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(TextAnnotationDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.dateTimeEdit_Start = QtWidgets.QDateTimeEdit(TextAnnotationDialog)
        self.dateTimeEdit_Start.setWrapping(True)
        self.dateTimeEdit_Start.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.dateTimeEdit_Start.setObjectName("dateTimeEdit_Start")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit_Start)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.label_2 = QtWidgets.QLabel(TextAnnotationDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dateTimeEdit_End = QtWidgets.QDateTimeEdit(TextAnnotationDialog)
        self.dateTimeEdit_End.setEnabled(True)
        self.dateTimeEdit_End.setWrapping(True)
        self.dateTimeEdit_End.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.dateTimeEdit_End.setObjectName("dateTimeEdit_End")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit_End)
        self.label_3 = QtWidgets.QLabel(TextAnnotationDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_Title = QtWidgets.QLineEdit(TextAnnotationDialog)
        self.lineEdit_Title.setClearButtonEnabled(True)
        self.lineEdit_Title.setObjectName("lineEdit_Title")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Title)
        self.label_4 = QtWidgets.QLabel(TextAnnotationDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_Subtitle = QtWidgets.QLineEdit(TextAnnotationDialog)
        self.lineEdit_Subtitle.setClearButtonEnabled(True)
        self.lineEdit_Subtitle.setObjectName("lineEdit_Subtitle")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Subtitle)
        self.label_5 = QtWidgets.QLabel(TextAnnotationDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.textBrowser_Body = QtWidgets.QTextBrowser(TextAnnotationDialog)
        self.textBrowser_Body.setReadOnly(False)
        self.textBrowser_Body.setObjectName("textBrowser_Body")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textBrowser_Body)
        self.checkBox_ShouldUseEndDate = QtWidgets.QCheckBox(TextAnnotationDialog)
        self.checkBox_ShouldUseEndDate.setChecked(True)
        self.checkBox_ShouldUseEndDate.setObjectName("checkBox_ShouldUseEndDate")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox_ShouldUseEndDate)
        self.frame_BoxExperCohortAnimalIDs = DialogComponents_BoxExperCohortAnimalIDs(TextAnnotationDialog)
        self.frame_BoxExperCohortAnimalIDs.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_BoxExperCohortAnimalIDs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BoxExperCohortAnimalIDs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_BoxExperCohortAnimalIDs.setObjectName("frame_BoxExperCohortAnimalIDs")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.frame_BoxExperCohortAnimalIDs)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(TextAnnotationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TextAnnotationDialog)
        self.buttonBox.accepted.connect(TextAnnotationDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(TextAnnotationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TextAnnotationDialog)

    def retranslateUi(self, TextAnnotationDialog):
        _translate = QtCore.QCoreApplication.translate
        TextAnnotationDialog.setWindowTitle(_translate("TextAnnotationDialog", "Text Annotation Edit Dialog"))
        self.label.setText(_translate("TextAnnotationDialog", "startDate"))
        self.label_2.setText(_translate("TextAnnotationDialog", "endDate"))
        self.label_3.setText(_translate("TextAnnotationDialog", "Title"))
        self.lineEdit_Title.setPlaceholderText(_translate("TextAnnotationDialog", "title"))
        self.label_4.setText(_translate("TextAnnotationDialog", "Subtitle"))
        self.lineEdit_Subtitle.setPlaceholderText(_translate("TextAnnotationDialog", "subtitle"))
        self.label_5.setText(_translate("TextAnnotationDialog", "Body"))
        self.textBrowser_Body.setPlaceholderText(_translate("TextAnnotationDialog", "body text"))
        self.checkBox_ShouldUseEndDate.setText(_translate("TextAnnotationDialog", "shouldUseEndDate"))
from GUI.UI.DialogComponents.DialogComponents_BoxExperCohortAnimalIDs import DialogComponents_BoxExperCohortAnimalIDs
