# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\TimelineHeaderWidget\TimelineHeaderWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frame_TimelineHeaderWidget(object):
    def setupUi(self, frame_TimelineHeaderWidget):
        frame_TimelineHeaderWidget.setObjectName("frame_TimelineHeaderWidget")
        frame_TimelineHeaderWidget.resize(376, 112)
        self.gridLayout = QtWidgets.QGridLayout(frame_TimelineHeaderWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.actionToggle_Track_Header_Collapsed = QtWidgets.QAction(frame_TimelineHeaderWidget)
        self.actionToggle_Track_Header_Collapsed.setCheckable(True)
        self.actionToggle_Track_Header_Collapsed.setEnabled(True)
        self.actionToggle_Track_Header_Collapsed.setObjectName("actionToggle_Track_Header_Collapsed")
        self.actionShow_Track_Options = QtWidgets.QAction(frame_TimelineHeaderWidget)
        self.actionShow_Track_Options.setCheckable(True)
        self.actionShow_Track_Options.setAutoRepeat(True)
        self.actionShow_Track_Options.setVisible(True)
        self.actionShow_Track_Options.setObjectName("actionShow_Track_Options")
        self.actionRefresh_Track = QtWidgets.QAction(frame_TimelineHeaderWidget)
        self.actionRefresh_Track.setCheckable(True)
        self.actionRefresh_Track.setObjectName("actionRefresh_Track")

        self.retranslateUi(frame_TimelineHeaderWidget)
        QtCore.QMetaObject.connectSlotsByName(frame_TimelineHeaderWidget)

    def retranslateUi(self, frame_TimelineHeaderWidget):
        _translate = QtCore.QCoreApplication.translate
        frame_TimelineHeaderWidget.setWindowTitle(_translate("frame_TimelineHeaderWidget", "Frame"))
        self.actionToggle_Track_Header_Collapsed.setText(_translate("frame_TimelineHeaderWidget", "Toggle Track Header Collapsed"))
        self.actionToggle_Track_Header_Collapsed.setToolTip(_translate("frame_TimelineHeaderWidget", "Toggles whether the track header is collapsed or revealed"))
        self.actionShow_Track_Options.setText(_translate("frame_TimelineHeaderWidget", "Show Track Options"))
        self.actionShow_Track_Options.setToolTip(_translate("frame_TimelineHeaderWidget", "Shows the configuration for the track"))
        self.actionRefresh_Track.setText(_translate("frame_TimelineHeaderWidget", "Refresh Track"))
        self.actionRefresh_Track.setToolTip(_translate("frame_TimelineHeaderWidget", "Reloads the track"))
