# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\TimelineHeaderWidget\TimelineHeaderWidget_ContentsExpanded.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimelineHeaderWidget_ContentsExpanded(object):
    def setupUi(self, TimelineHeaderWidget_ContentsExpanded):
        TimelineHeaderWidget_ContentsExpanded.setObjectName("TimelineHeaderWidget_ContentsExpanded")
        TimelineHeaderWidget_ContentsExpanded.resize(379, 300)
        TimelineHeaderWidget_ContentsExpanded.setAutoFillBackground(False)
        TimelineHeaderWidget_ContentsExpanded.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(30, 30, 30, 200), stop:1 rgba(60, 66, 60, 200));\n"
"color:rgb(243, 243, 243);\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(TimelineHeaderWidget_ContentsExpanded)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_TopButtons = QtWidgets.QFrame(TimelineHeaderWidget_ContentsExpanded)
        self.frame_TopButtons.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_TopButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopButtons.setObjectName("frame_TopButtons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_TopButtons)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblTitle = QtWidgets.QLabel(self.frame_TopButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: rgb(250, 250, 250)")
        self.lblTitle.setObjectName("lblTitle")
        self.horizontalLayout_3.addWidget(self.lblTitle)
        self.btnToggleCollapse = QtWidgets.QPushButton(self.frame_TopButtons)
        self.btnToggleCollapse.setText("")
        self.btnToggleCollapse.setObjectName("btnToggleCollapse")
        self.horizontalLayout_3.addWidget(self.btnToggleCollapse)
        self.btnOptions = QtWidgets.QPushButton(self.frame_TopButtons)
        self.btnOptions.setText("")
        self.btnOptions.setObjectName("btnOptions")
        self.horizontalLayout_3.addWidget(self.btnOptions)
        self.btnRefresh = QtWidgets.QPushButton(self.frame_TopButtons)
        self.btnRefresh.setText("")
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_3.addWidget(self.btnRefresh)
        self.verticalLayout.addWidget(self.frame_TopButtons)
        self.textBrowser_Main = QtWidgets.QTextBrowser(TimelineHeaderWidget_ContentsExpanded)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_Main.setFont(font)
        self.textBrowser_Main.setAcceptDrops(False)
        self.textBrowser_Main.setStyleSheet("background-color: rgba(179, 215, 255, 80)")
        self.textBrowser_Main.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textBrowser_Main.setOpenLinks(False)
        self.textBrowser_Main.setObjectName("textBrowser_Main")
        self.verticalLayout.addWidget(self.textBrowser_Main)

        self.retranslateUi(TimelineHeaderWidget_ContentsExpanded)
        QtCore.QMetaObject.connectSlotsByName(TimelineHeaderWidget_ContentsExpanded)

    def retranslateUi(self, TimelineHeaderWidget_ContentsExpanded):
        _translate = QtCore.QCoreApplication.translate
        TimelineHeaderWidget_ContentsExpanded.setWindowTitle(_translate("TimelineHeaderWidget_ContentsExpanded", "TimelineHeaderWidget_ContentsExpanded"))
        self.lblTitle.setText(_translate("TimelineHeaderWidget_ContentsExpanded", "Track 00"))
        self.btnToggleCollapse.setToolTip(_translate("TimelineHeaderWidget_ContentsExpanded", "Collapse"))
        self.btnToggleCollapse.setStatusTip(_translate("TimelineHeaderWidget_ContentsExpanded", "Collapse"))
        self.btnToggleCollapse.setAccessibleName(_translate("TimelineHeaderWidget_ContentsExpanded", "Collapse"))
        self.btnOptions.setToolTip(_translate("TimelineHeaderWidget_ContentsExpanded", "Options"))
        self.btnOptions.setStatusTip(_translate("TimelineHeaderWidget_ContentsExpanded", "Options"))
        self.btnOptions.setAccessibleName(_translate("TimelineHeaderWidget_ContentsExpanded", "Options"))
        self.btnRefresh.setToolTip(_translate("TimelineHeaderWidget_ContentsExpanded", "Refresh"))
        self.btnRefresh.setStatusTip(_translate("TimelineHeaderWidget_ContentsExpanded", "Refresh"))
        self.btnRefresh.setAccessibleName(_translate("TimelineHeaderWidget_ContentsExpanded", "Refresh"))
        self.textBrowser_Main.setDocumentTitle(_translate("TimelineHeaderWidget_ContentsExpanded", "test"))
        self.textBrowser_Main.setPlaceholderText(_translate("TimelineHeaderWidget_ContentsExpanded", "this is a multiline test"))
