# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\TimelineHeaderWidget\TimelineHeaderWidget_ContentsCollapsed.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimelineHeaderWidget_ContentsCollapsed(object):
    def setupUi(self, TimelineHeaderWidget_ContentsCollapsed):
        TimelineHeaderWidget_ContentsCollapsed.setObjectName("TimelineHeaderWidget_ContentsCollapsed")
        TimelineHeaderWidget_ContentsCollapsed.resize(94, 122)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TimelineHeaderWidget_ContentsCollapsed.sizePolicy().hasHeightForWidth())
        TimelineHeaderWidget_ContentsCollapsed.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimelineHeaderWidget_ContentsCollapsed)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(TimelineHeaderWidget_ContentsCollapsed)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(TimelineHeaderWidget_ContentsCollapsed)
        QtCore.QMetaObject.connectSlotsByName(TimelineHeaderWidget_ContentsCollapsed)

    def retranslateUi(self, TimelineHeaderWidget_ContentsCollapsed):
        _translate = QtCore.QCoreApplication.translate
        TimelineHeaderWidget_ContentsCollapsed.setWindowTitle(_translate("TimelineHeaderWidget_ContentsCollapsed", "TimelineHeaderWidget_ContentsCollapsed"))
