# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\PhoPyQtTimelinePlotter\src\phopyqttimelineplotter\GUI\UI\VideoTrackFilterEditWidget\VideoTrackFilterEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoTrackFilterEditDialog(object):
    def setupUi(self, VideoTrackFilterEditDialog):
        VideoTrackFilterEditDialog.setObjectName("VideoTrackFilterEditDialog")
        VideoTrackFilterEditDialog.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(VideoTrackFilterEditDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(VideoTrackFilterEditDialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lblTrackID = QtWidgets.QLabel(VideoTrackFilterEditDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTrackID.sizePolicy().hasHeightForWidth())
        self.lblTrackID.setSizePolicy(sizePolicy)
        self.lblTrackID.setObjectName("lblTrackID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblTrackID)
        self.label_3 = QtWidgets.QLabel(VideoTrackFilterEditDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lblTrackName = QtWidgets.QLabel(VideoTrackFilterEditDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTrackName.sizePolicy().hasHeightForWidth())
        self.lblTrackName.setSizePolicy(sizePolicy)
        self.lblTrackName.setObjectName("lblTrackName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblTrackName)
        self.verticalLayout.addLayout(self.formLayout)
        self.checkBox_isOriginalVideo = QtWidgets.QCheckBox(VideoTrackFilterEditDialog)
        self.checkBox_isOriginalVideo.setObjectName("checkBox_isOriginalVideo")
        self.verticalLayout.addWidget(self.checkBox_isOriginalVideo)
        self.checkBox_isTaggedVideo = QtWidgets.QCheckBox(VideoTrackFilterEditDialog)
        self.checkBox_isTaggedVideo.setObjectName("checkBox_isTaggedVideo")
        self.verticalLayout.addWidget(self.checkBox_isTaggedVideo)
        self.frame_BoxExperCohortAnimalIDs = DialogComponents_BoxExperCohortAnimalIDs(VideoTrackFilterEditDialog)
        self.frame_BoxExperCohortAnimalIDs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BoxExperCohortAnimalIDs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_BoxExperCohortAnimalIDs.setObjectName("frame_BoxExperCohortAnimalIDs")
        self.verticalLayout.addWidget(self.frame_BoxExperCohortAnimalIDs)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(VideoTrackFilterEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(VideoTrackFilterEditDialog)
        self.buttonBox.accepted.connect(VideoTrackFilterEditDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(VideoTrackFilterEditDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VideoTrackFilterEditDialog)

    def retranslateUi(self, VideoTrackFilterEditDialog):
        _translate = QtCore.QCoreApplication.translate
        VideoTrackFilterEditDialog.setWindowTitle(_translate("VideoTrackFilterEditDialog", "Dialog"))
        self.label.setText(_translate("VideoTrackFilterEditDialog", "Track ID:"))
        self.lblTrackID.setText(_translate("VideoTrackFilterEditDialog", "0000"))
        self.label_3.setText(_translate("VideoTrackFilterEditDialog", "Track Name:"))
        self.lblTrackName.setText(_translate("VideoTrackFilterEditDialog", "Name"))
        self.checkBox_isOriginalVideo.setText(_translate("VideoTrackFilterEditDialog", "is Original Video"))
        self.checkBox_isTaggedVideo.setText(_translate("VideoTrackFilterEditDialog", "is Tagged Video"))
from GUI.UI.DialogComponents.DialogComponents_BoxExperCohortAnimalIDs import DialogComponents_BoxExperCohortAnimalIDs
